# Generated by Django 3.0.5 on 2020-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerish', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
